import {
  ITEM_DETAIL_URL,
  USER_DETAIL_URL,
  WALLET_QUERY_URL,
  TRAN_QUERY_URL,
  CONTRACT_QUERY_URL,
} from "../../config/urlDefine";
export const summaryKeyList = [
  { title: "기간", isDate: true },
  { title: "회원" },
  { title: "거래", hasChildren: true, numChildren: 2 },
  { title: "건수", isChildren: true },
  { title: "금액 (USD)", isChildren: true },
  { title: "수수료", hasChildren: true, numChildren: 2 },
  { title: "건수", isChildren: true },
  { title: "금액 (USD)", isChildren: true },
  { title: "로얄티", hasChildren: true, numChildren: 2 },
  { title: "건수", isChildren: true },
  { title: "금액 (USD)", isChildren: true },
  // { title: "레퍼럴", hasChildren: true, numChildren: 2 },
  // { title: "건수", isChildren: true },
  // { title: "금액 (USD)", isChildren: true },
];

export const summaryKeyToValue = [
  "term",
  "member",
  "trade",
  "fee",
  "royal",
  // "ref",
];
export const tradeKeyList = [
  { title: "No" },
  { title: "거래 일시", isDate: true },
  { title: "ITEM", hasChildren: true, numChildren: 4 },
  { title: "item name", isChildren: true, href: ITEM_DETAIL_URL + `?itemId=` },
  { title: "ItemID", isChildren: true },
  { title: "아이템 토큰", isChildren: true },
  { title: "아이템 가격", isChildren: true },
  { title: "거래", hasChildren: true, numChildren: 10 },
  { title: "거래 번호", isChildren: true },
  { title: "거래 방식", isChildren: true, convertInt: ["고정 가격", "경매"] },
  { title: "체결 상태", isChildren: true },
  { title: "결제 토큰", isChildren: true },
  { title: "결제 금액", isChildren: true },
  { title: "결제 액수 (USD)", isChildren: true },
  { title: "From", isChildren: true, href: USER_DETAIL_URL + "?userId=" },
  { title: "To", isChildren: true, href: USER_DETAIL_URL + "?userId=" },
  { title: "Transaction", isChildren: true, href: TRAN_QUERY_URL },
];
export const tradeKeyToValue = [
  "no",
  "date",
  "itemName",
  "itemId",
  "itemToken",
  "itemPrice",
  "tradeNo",
  "tradeRoute",
  "tradeState",
  "tradeToken",
  "tradePrice",
  "tradeUSD",
  "from",
  "to",
  "transaction",
];
export const feeKeyList = [
  { title: "No" },
  { title: "거래 일시", isDate: true },
  { title: "Event" },
  { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
  { title: "ItemID" },
  { title: "아이템 토큰" },
  { title: "아이템 가격" },
  { title: "결제 토큰" },
  { title: "결제 금액" },
  { title: "결제 액수 (USD)" },
  { title: "수수료" },
  { title: "From", href: USER_DETAIL_URL + "?userId=" },
  { title: "To", href: USER_DETAIL_URL + "?userId=" },
  { title: "Transaction", href: TRAN_QUERY_URL },
];
export const feeKeyToValue = [
  "no",
  "date",
  "event",
  "itemName",
  "itemId",
  "itemToken",
  "itemPrice",
  "tradeToken",
  "payPrice",
  "tradeUSD",
  "fee",
  "from",
  "to",
  "transaction",
];
// export const refKeyList = [
//   { title: "No" },
//   { title: "거래 일시", isDate: true },
//   { title: "지급 일시" },
//   { title: "Event" },
//   { title: "레퍼럴 수령자" },
//   { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
//   { title: "결제 토큰" },
//   { title: "결제 수량" },
//   { title: "결제 가격 (USD)" },
//   { title: "From", href: USER_DETAIL_URL + "?userId=" },
//   { title: "To", href: USER_DETAIL_URL + "?userId=" },
//   { title: "레퍼럴 토큰" },
//   { title: "레퍼럴 금액" },
//   { title: "레퍼럴 액수 (USD)" },
//   { title: "지급 상태", convertInt: ["대기", "지불 완료"] },
//   { title: "transaction", href: TRAN_QUERY_URL },
// ];
// export const refKeyToValue = [
//   "no",
//   "tradeDate",
//   "payDate",
//   "event",
//   "itemName",
//   "itemToken",
//   "itemPrice",
//   "tradeUSD",
//   "from",
//   "to",
//   "refToken",
//   "refPrice",
//   "refUSD",
//   "payState",
//   "transaction",
// ];
export const royalKeyList = [
  { title: "No" },
  { title: "거래 일시", isDate: true },
  { title: "지급 일시" },
  { title: "Event" },
  { title: "Creator" },
  { title: "item name", diffhref: ITEM_DETAIL_URL + "?itemId=" },
  { title: "결제 토큰" },
  { title: "결제 수량" },
  { title: "결제 가격 (USD)" },
  { title: "From", href: USER_DETAIL_URL + "?userId" },
  { title: "To", href: USER_DETAIL_URL + "?userId" },
  { title: "로열티 토큰" },
  { title: "로열티 금액" },
  { title: "로열티 액수 (USD)" },
  { title: "지급 상태", convertInt: ["대기", "지불 완료"] },
  { title: "transaction", href: TRAN_QUERY_URL },
];
export const royalKeyToValue = [
  "no",
  "tradeDate",
  "payDate",
  "event",
  "creator",
  "itemName",
  "itemToken",
  "itemPrice",
  "tradeUSD",
  "from",
  "to",
  "royalToken",
  "royalPrice",
  "royalUSD",
  "payState",
  "transaction",
];
