import {
  ITEM_DETAIL_URL,
  USER_DETAIL_URL,
  STATISTICS_DETAIL_URL,
  NOTICE_DETAIL_URL,
  WALLET_QUERY_URL,
  CONTRACT_QUERY_URL,
  TRAN_QUERY_URL,
} from "../../config/urlDefine";
export const mainCategory = [
  {
    title: "Wallet",
    subCategory: [
      {
        title: "Buy",
        keyList: [
          { title: "No" },
          { title: "거래 일시", isDate: true },
          { title: "ITEM", hasChildren: true, numChildren: 4 },
          {
            title: "item name",
            isChildren: true,
            href: ITEM_DETAIL_URL + `?itemId=`,
          },
          { title: "item ID", isChildren: true },
          { title: "아이템 토큰", isChildren: true },
          { title: "아이템 가격", isChildren: true },
          { title: "Buy", hasChildren: true, numChildren: 10 },
          { title: "거래 번호", isChildren: true },
          { title: "거래 방식", isChildren: true },
          { title: "체결 상태", isChildren: true },
          { title: "결제 토큰", isChildren: true },
          { title: "결제 금액", isChildren: true },
          { title: "결제 액수 (USD)", isChildren: true },
          {
            title: "From",
            isChildren: true,
            href: USER_DETAIL_URL + "?userId=",
          },
          { title: "To", isChildren: true, href: USER_DETAIL_URL + "?userId=" },
          { title: "수수료", isChildren: true },
          {
            title: "Transaction",
            isChildren: true,
            href: TRAN_QUERY_URL,
          },
        ],
      },
      {
        title: "Sale",
        keyList: [
          { title: "No" },
          { title: "거래 일시", isDate: true },
          { title: "ITEM", hasChildren: true, numChildren: 4 },
          {
            title: "item name",
            isChildren: true,
            href: ITEM_DETAIL_URL + "?itemId=",
          },
          { title: "itemID", isChildren: true },
          { title: "아이템 토큰", isChildren: true },
          { title: "아이템 가격", isChildren: true },
          { title: "Sale", hasChildren: true, numChildren: 10 },
          { title: "거래 번호", isChildren: true },
          { title: "거래 방식", isChildren: true },
          { title: "체결 상태", isChildren: true },
          { title: "결제 토큰", isChildren: true },
          { title: "결제 금액", isChildren: true },
          { title: "결제 액수 (USD)", isChildren: true },
          {
            title: "From",
            isChildren: true,
            href: USER_DETAIL_URL + "?userId=",
          },
          { title: "To", isChildren: true, href: USER_DETAIL_URL + "?userId=" },
          { title: "수수료", isChildren: true },
          { title: "Transaction", isChildren: true, href: TRAN_QUERY_URL },
        ],
      },
      {
        title: "수수료",
        keyList: [
          { title: "No" },
          { title: "거래 일시", isDate: true },
          { title: "Event" },
          { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
          { title: "itemID" },
          { title: "아이템 토큰" },
          { title: "아이템 가격" },
          { title: "결제 토큰" },
          { title: "결제 금액" },
          { title: "결제 액수 (USD)" },
          { title: "수수료" },
          { title: "수수료 액수 (USD)" },
          { title: "From", href: USER_DETAIL_URL + `?userId=` },
          { title: "To", href: USER_DETAIL_URL + "?userId=" },
          { title: "Transaction", href: TRAN_QUERY_URL },
        ],
      },
      {
        title: "로얄티",
        keyList: [
          { title: "No" },
          { title: "거래 일시" },
          { title: "지급 일시", isDate: true },
          { title: "Event" },
          { title: "Creator", href: USER_DETAIL_URL + "?userId=" },
          { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
          { title: "결제 토큰" },
          { title: "결제 수량" },
          { title: "결제 가격 (USD)" },
          { title: "From", href: USER_DETAIL_URL + "?userId=" },
          { title: "To", href: USER_DETAIL_URL + "?userId=" },
          { title: "로열티 토큰" },
          { title: "로열티 금액" },
          { title: "로열티 액수 (USD)" },
          {
            title: "지급 상태",
            convertInt: ["전체", "대기", "지급 완료"],
            filter: true,
          },
          { title: "Transaction", href: TRAN_QUERY_URL },
        ],
      },
      {
        title: "레퍼럴",
        keyList: [
          { title: "No" },
          { title: "거래 일시" },
          { title: "지급 일시", isDate: true },
          { title: "Event" },
          { title: "레퍼럴 수령자" },
          { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
          { title: "결제 토큰" },
          { title: "결제 수량" },
          { title: "결제 가격 (USD)" },
          { title: "From", href: USER_DETAIL_URL + "?userId=" },
          { title: "To", href: USER_DETAIL_URL + "?userId=" },
          { title: "레퍼럴 토큰" },
          { title: "레퍼럴 금액" },
          { title: "레퍼럴 액수 (USD)" },
          {
            title: "지급 상태",
            convertInt: ["전체", "대기", "지급 완료"],
            filter: true,
          },
          { title: "Transaction", href: TRAN_QUERY_URL },
        ],
      },
    ],
  },
  {
    title: "Items",
    keyList: [
      { title: "No" },
      { title: "등록 일시", isDate: true },
      { title: "Creator", href: USER_DETAIL_URL + `?userId=` },
      { title: "Owner" },
      { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
      { title: "item ID" },
      { title: "Category" },
      { title: "아이템 토큰" },
      { title: "아이템 가격" },
      { title: "Contract", href: CONTRACT_QUERY_URL },
    ],
  },
  {
    title: "Activity",
    keyList: [
      { title: "거래 번호" },
      { title: "Date", isDate: true },
      {
        title: "Event",
        convertInt: [
          "Create",
          "Minted",
          "Cancel",
          "bid",
          "sale",
          "Transfer",
          "listing",
        ],
        filter: true,
      },
      { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
      { title: "item ID" },
      { title: "코인" },
      { title: "가격" },
      { title: "From", href: USER_DETAIL_URL + "?userId=" },
      { title: "To", href: USER_DETAIL_URL + "?userId=" },
      { title: "Transaction", href: TRAN_QUERY_URL },
    ],
  },
  {
    title: "Offer",
    keyList: [
      { title: "No" },
      { title: "offer 시간" },
      { title: "offer 완료일", isDate: true },
      {
        title: "offer",
        filter: true,
        convertInt: ["전체", "제안 Offer", "입찰 Offer"],
      },
      {
        title: "offer 결과",
        convertInt: ["전체", "진행 중", "Expired", "판매 종료", "판매 체결"],
        filter: true,
      },
      {
        title: "거래 구분",
        filter: true,
        convertInt: ["고정 가격", "최저가 경매", "최고가 경매"],
      },
      { title: "item", href: ITEM_DETAIL_URL + "?itemId=" },
      { title: "item 코인" },
      { title: "item price" },
      { title: "offer 코인" },
      { title: "offer Price" },
      { title: "Quantity" },
      { title: "From" },
      { title: "To" },
    ],
  },
  {
    title: "Favorites",
    keyList: [
      { title: "No" },
      { title: "등록 일시", isDate: true },
      { title: "Owner", href: USER_DETAIL_URL + "?userId=" },
      { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
      { title: "itemID" },
      { title: "아이템 토큰" },
      { title: "아이템 가격" },
      { title: "Contract", href: CONTRACT_QUERY_URL },
    ],
  },
  {
    title: "HideItem",
    keyList: [
      { title: "No" },
      { title: "등록 일시", isDate: true },
      { title: "Owner", href: USER_DETAIL_URL + "?userId=" },
      { title: "item name", href: ITEM_DETAIL_URL + "?itemId=" },
      { title: "itemID" },
      { title: "아이템 토큰" },
      { title: "아이템 가격" },
      { title: "Contract", href: CONTRACT_QUERY_URL },
    ],
  },
];
