import moment from "moment";
export const Mockups = [
  {
    title: "wallet",
    subMokups: [
      {
        title: "buy",
        tableData: [
          {
            no: 1,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
          {
            no: 2,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
          {
            no: 3,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
        ],
      },
      {
        title: "sale",
        tableData: [
          {
            no: 1,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
          {
            no: 2,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
          {
            no: 3,
            tradeDate: moment().format("2021-06-12 09:50:11"),
            itemName: "NFTitem1",
            itemId: "351...5",
            payToken: "KLAY",
            payAmount: 1,
            tradeNumber: "Or13",
            tradeMethod: "경매 입찰",
            tradeState: "완료",
            payTokenBuy: "KLAY",
            payAmountBuy: 1,
            payUSD: 30.45,
            From: "jaflee",
            To: "dkslek",
            fee: 0.25,
            transaction: "OX13kadnfwr23",
          },
        ],
      },
      {
        title: "Feeds",
        tableData: [
          {
            no: 1,
            tradeDate: moment().format("2021-06-21 09:50:11"),
            event: "BUY",
            itemName: "NFTitem1",
            itemId: "131....5",
            itemToken: "KLAY",
            itemPrice: 1,
            payToken: "KLAY",
            payPrice: 1,
            payUSD: 30.45,
            feeds: 0.25,
            payUSD2: 30.45,
            From: "dkelwk",
            to: "jafflee",
            transaction: "OX13ska2214soek",
          },
        ],
      },
      {
        title: "Royal",
        tableData: [
          {
            no: 1,
            tradeDate: moment().format("2021-06-21 09:50:11"),
            payDate: moment().format("2021-06-21 09:50:11"),
            event: "BUY",
            creator: "creator1",
            itemName: "NFTitem1",
            itemToken: "KLAY",
            itemPrice: 1,
            payUSD: 30.45,
            From: "dkelwk",
            to: "jafflee",
            payToken: "KLAY",
            feeds: 0.05,
            payUSD2: 10.45,
            supState: 1,
            transaction: "OX13ska2214soek",
          },
        ],
      },
      {
        title: "Refferal",
        tableData: [
          {
            no: 1,
            tradeDate: moment().format("2021-06-21 09:50:11"),
            payDate: moment().format("2021-06-21 09:50:11"),
            event: "BUY",
            creator: "reffer1",
            itemName: "NFTitem1",
            itemToken: "KLAY",
            itemPrice: 1,
            payUSD: 30.45,
            From: "dkelwk",
            to: "jafflee",
            payToken: "KLAY",
            feeds: 0.05,
            payUSD2: 10.45,
            supState: 0,
            transaction: "OX13ska2214soek",
          },
        ],
      },
    ],
  },
  {
    title: "Items",
    tableData: [
      {
        no: 1,
        regDate: moment().format("2021-06-12 09:50:11"),
        creator: "creator1",
        owner: "jafflee",
        itemName: "NFTitem1",
        itemID: "351..5",
        category: "Art",
        itemToken: "KLAY",
        itemPrice: 1,
        contract: "Ox1312312312",
      },
    ],
  },
  {
    title: "Activity",
    tableData: [
      {
        no: "Or13",
        regDate: moment().format("2021-06-12 09:50:11"),
        event: 1,
        itemName: "NFTitem1",
        itemID: "351..5",
        itemToken: "WETH",
        price: 2.15,
        from: "jafflee",
        to: "akfjdl",
        contract: "Ox1312312312",
      },
    ],
  },
  {
    title: "Offer",
    tableData: [
      {
        no: "1",
        regDate: moment().format("2021-06-12 09:50:11"),
        Date: moment().format("2021-06-12 09:50:11"),
        offer: 1,
        offerresult: 1,
        kind: 2,
        itemName: "NFTitem2",
        itemToken: "WETH",
        price: 2.15,
        offerCoin: "ETH",
        Offerprice: 2.15,
        quantity: 1,
        from: "jafflee",
        to: "akfjdl",
      },
      {
        no: "2",
        regDate: moment().format("2021-06-12 09:50:11"),
        Date: moment().format("2021-06-12 09:50:11"),
        offer: 2,
        offerresult: 0,
        kind: 2,
        itemName: "NFTitem3",
        itemToken: "WETH",
        price: 2.15,
        offerCoin: "ETH",
        Offerprice: 2.15,
        quantity: 1,
        from: "jafflee",
        to: "akfjdl",
      },
      {
        no: "3",
        regDate: moment().format("2021-06-12 09:50:11"),
        Date: moment().format("2021-06-12 09:50:11"),
        offer: 0,
        offerresult: 2,
        kind: 1,
        itemName: "NFTitem3",
        itemToken: "WETH",
        price: 2.15,
        offerCoin: "ETH",
        Offerprice: 2.15,
        quantity: 1,
        from: "jafflee",
        to: "akfjdl",
      },
      {
        no: "4",
        regDate: moment().format("2021-06-12 09:50:11"),
        Date: moment().format("2021-06-12 09:50:11"),
        offer: 2,
        offerresult: 3,
        kind: 0,
        itemName: "NFTitem4",
        itemToken: "WETH",
        price: 2.15,
        offerCoin: "ETH",
        Offerprice: 2.15,
        quantity: 1,
        from: "jafflee",
        to: "akfjdl",
      },
      {
        no: "5",
        regDate: moment().format("2021-06-12 09:50:11"),
        Date: moment().format("2021-06-12 09:50:11"),
        offer: 2,
        offerresult: 4,
        kind: 0,
        itemName: "NFTitem5",
        itemToken: "WETH",
        price: 2.15,
        offerCoin: "ETH",
        Offerprice: 2.15,
        quantity: 1,
        from: "jafflee",
        to: "akfjdl",
      },
    ],
  },
  {
    title: "favorite",
    tableData: [
      {
        no: "1",
        regDate: moment().format("2021-06-12 09:50:11"),
        owner: "fsdff321ss",
        itemName: "NFTitem1",
        itemID: "351..5",
        itemToken: "KLAY",
        price: 1,
        contract: "Ox1312312312",
      },
    ],
  },
  {
    title: "hidden",
    tableData: [
      {
        no: "1",
        regDate: moment().format("2021-06-12 09:50:11"),
        owner: "fsdff321ss",
        itemName: "NFTitem3",
        itemID: "351..5",
        itemToken: "KLAY",
        price: 1,
        contract: "OxHIDDEN",
      },
    ],
  },
];
